### ISSUE TITLE
Sound error

### ISSUE THREAD

**Issue by JMankewitz** [rholson1/tobii_calibration#2]
When we calibrate, it seems we're having an issue with sound. We're getting the following stack:

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\mankewitz\.conda\envs\compshapes_py310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\mankewitz\.conda\envs\compshapes_py310\lib\tkinter\__init__.py", line 839, in callit
    func(*args)
  File "C:\Experiment\psychopy\tobii_calibration\tobii_calibration.py", line 372, in run_calibration
    self.play_sound()
  File "C:\Experiment\psychopy\tobii_calibration\tobii_calibration.py", line 478, in play_sound
    stream = self.pyaudio.open(format=self.pyaudio.get_format_from_width(self.wave_samplewidth),
  File "C:\Users\mankewitz\.conda\envs\compshapes_py310\lib\site-packages\pyaudio\__init__.py", line 639, in open
    stream = PyAudio.Stream(self, *args, **kwargs)
  File "C:\Users\mankewitz\.conda\envs\compshapes_py310\lib\site-packages\pyaudio\__init__.py", line 441, in __init__
    self._stream = pa.open(**arguments)
OSError: [Errno -9998] Invalid number of channels
```

Note: we're using the sound device 1

Maybe something is up with pyaudio? We typically use psychopy/ptb on these machines

**Comment by rholson1** [comment]
I suggest trying a different sound device.  I suspect sound device 1 is input only so it has no output channels.
You could use something like the following to learn more about the available devices:
```

import pyaudio
p = pyaudio.PyAudio()
for i in range(p.get_device_count()):
   d = p.get_device_info_by_index(i)
   print(f"index: {i}, {d['name']}, input={d['maxInputChannels']}, output={d['maxOutputChannels']}")

```
